name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MarketProject/
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./MarketProject/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./MarketProject/
      
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MarketProject/
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./MarketProject/

