name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  Build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MarketProject/
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./MarketProject/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./MarketProject/
      
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MarketProject/
    - name: Test
      run: dotnet test --verbosity normal
      working-directory: ./MarketProject/

